// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALpiN70qBN6oHDHk9xDaiNYQXdJXDeiqI',
    appId: '1:999694322267:web:8c380714bcf2452dd20d7e',
    messagingSenderId: '999694322267',
    projectId: 'reddit-practise-yeasin',
    authDomain: 'reddit-practise-yeasin.firebaseapp.com',
    storageBucket: 'reddit-practise-yeasin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkh1JsS4DZrRkEIi-8PB5C1a72zEr6ylc',
    appId: '1:999694322267:android:9cb4837e6e202c01d20d7e',
    messagingSenderId: '999694322267',
    projectId: 'reddit-practise-yeasin',
    storageBucket: 'reddit-practise-yeasin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMSrX1Y5-faNJ03uySuKPgVTb5Oerj3no',
    appId: '1:999694322267:ios:4960109a904e403dd20d7e',
    messagingSenderId: '999694322267',
    projectId: 'reddit-practise-yeasin',
    storageBucket: 'reddit-practise-yeasin.appspot.com',
    iosClientId: '999694322267-19mc545h76okjh5v3m5oq6u7sq283qoo.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
